/*
  File autogenerated by gengetopt version 2.21
  generated with the following command:
  gengetopt 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: rhydrogen [OPTIONS]...";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                Print help and exit",
  "  -V, --version             Print version and exit",
  "\nAll of the following flags are required\n",
  "  -N, --number-gridpts=INT  Number of grid points, e.g. 100",
  "  -s, --scale-param=INT     Scale parameter, e.g. 4000",
  "  -l, --l-orbital-qn=FLOAT  Orbital angular momentum quantum number, e.g. for H \n                              1s electron orbit it would be 0, etc",
  "  -j, --j-total-qn=FLOAT    Total angular momentum quantum number, e.g. for H \n                              1s electon orbit (l = 0, s = 1/2) it would be \n                              0+0.5 = 0.5, etc",
  "  -Z, --Z-nucl-charge=INT   Charge of nucleus, e.g. 2 for alpha, etc.",
    0
};

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->number_gridpts_given = 0 ;
  args_info->scale_param_given = 0 ;
  args_info->l_orbital_qn_given = 0 ;
  args_info->j_total_qn_given = 0 ;
  args_info->Z_nucl_charge_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->number_gridpts_orig = NULL;
  args_info->scale_param_orig = NULL;
  args_info->l_orbital_qn_orig = NULL;
  args_info->j_total_qn_orig = NULL;
  args_info->Z_nucl_charge_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{
  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->number_gridpts_help = gengetopt_args_info_help[2] ;
  args_info->scale_param_help = gengetopt_args_info_help[3] ;
  args_info->l_orbital_qn_help = gengetopt_args_info_help[4] ;
  args_info->j_total_qn_help = gengetopt_args_info_help[5] ;
  args_info->Z_nucl_charge_help = gengetopt_args_info_help[6] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  printf("\n%s\n\n", gengetopt_args_info_usage);

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n", gengetopt_args_info_description);

  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

struct cmdline_parser_params *
cmdline_parser_params_init()
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));

  if (params)
    { 
      params->override = 0;
      params->initialize = 0;
      params->check_required = 0;
      params->check_ambiguity = 0;
    }
    
  return params;
}

static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  
  if (args_info->number_gridpts_orig)
    {
      free (args_info->number_gridpts_orig); /* free previous argument */
      args_info->number_gridpts_orig = 0;
    }
  if (args_info->scale_param_orig)
    {
      free (args_info->scale_param_orig); /* free previous argument */
      args_info->scale_param_orig = 0;
    }
  if (args_info->l_orbital_qn_orig)
    {
      free (args_info->l_orbital_qn_orig); /* free previous argument */
      args_info->l_orbital_qn_orig = 0;
    }
  if (args_info->j_total_qn_orig)
    {
      free (args_info->j_total_qn_orig); /* free previous argument */
      args_info->j_total_qn_orig = 0;
    }
  if (args_info->Z_nucl_charge_orig)
    {
      free (args_info->Z_nucl_charge_orig); /* free previous argument */
      args_info->Z_nucl_charge_orig = 0;
    }
  
  clear_given (args_info);
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  if (args_info->help_given) {
    fprintf(outfile, "%s\n", "help");
  }
  if (args_info->version_given) {
    fprintf(outfile, "%s\n", "version");
  }
  if (args_info->number_gridpts_given) {
    if (args_info->number_gridpts_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "number-gridpts", args_info->number_gridpts_orig);
    } else {
      fprintf(outfile, "%s\n", "number-gridpts");
    }
  }
  if (args_info->scale_param_given) {
    if (args_info->scale_param_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "scale-param", args_info->scale_param_orig);
    } else {
      fprintf(outfile, "%s\n", "scale-param");
    }
  }
  if (args_info->l_orbital_qn_given) {
    if (args_info->l_orbital_qn_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "l-orbital-qn", args_info->l_orbital_qn_orig);
    } else {
      fprintf(outfile, "%s\n", "l-orbital-qn");
    }
  }
  if (args_info->j_total_qn_given) {
    if (args_info->j_total_qn_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "j-total-qn", args_info->j_total_qn_orig);
    } else {
      fprintf(outfile, "%s\n", "j-total-qn");
    }
  }
  if (args_info->Z_nucl_charge_given) {
    if (args_info->Z_nucl_charge_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "Z-nucl-charge", args_info->Z_nucl_charge_orig);
    } else {
      fprintf(outfile, "%s\n", "Z-nucl-charge");
    }
  }
  
  fclose (outfile);

  i = EXIT_SUCCESS;
  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}


/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;

  result = cmdline_parser_internal (argc, argv, args_info, &params, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, NULL) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;

  /* checks for required options */
  if (! args_info->number_gridpts_given)
    {
      fprintf (stderr, "%s: '--number-gridpts' ('-N') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  
  if (! args_info->scale_param_given)
    {
      fprintf (stderr, "%s: '--scale-param' ('-s') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  
  if (! args_info->l_orbital_qn_given)
    {
      fprintf (stderr, "%s: '--l-orbital-qn' ('-l') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  
  if (! args_info->j_total_qn_given)
    {
      fprintf (stderr, "%s: '--j-total-qn' ('-j') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  
  if (! args_info->Z_nucl_charge_given)
    {
      fprintf (stderr, "%s: '--Z-nucl-charge' ('-Z') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  
  
  /* checks for dependences among options */

  return error;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "number-gridpts",	1, NULL, 'N' },
        { "scale-param",	1, NULL, 's' },
        { "l-orbital-qn",	1, NULL, 'l' },
        { "j-total-qn",	1, NULL, 'j' },
        { "Z-nucl-charge",	1, NULL, 'Z' },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVN:s:l:j:Z:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'N':	/* Number of grid points, e.g. 100.  */
          if (local_args_info.number_gridpts_given || (check_ambiguity && args_info->number_gridpts_given))
            {
              fprintf (stderr, "%s: `--number-gridpts' (`-N') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->number_gridpts_given && ! override)
            continue;
          local_args_info.number_gridpts_given = 1;
          args_info->number_gridpts_given = 1;
          args_info->number_gridpts_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->number_gridpts_orig)
            free (args_info->number_gridpts_orig); /* free previous string */
          args_info->number_gridpts_orig = gengetopt_strdup (optarg);
          break;

        case 's':	/* Scale parameter, e.g. 4000.  */
          if (local_args_info.scale_param_given || (check_ambiguity && args_info->scale_param_given))
            {
              fprintf (stderr, "%s: `--scale-param' (`-s') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->scale_param_given && ! override)
            continue;
          local_args_info.scale_param_given = 1;
          args_info->scale_param_given = 1;
          args_info->scale_param_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->scale_param_orig)
            free (args_info->scale_param_orig); /* free previous string */
          args_info->scale_param_orig = gengetopt_strdup (optarg);
          break;

        case 'l':	/* Orbital angular momentum quantum number, e.g. for H 1s electron orbit it would be 0, etc.  */
          if (local_args_info.l_orbital_qn_given || (check_ambiguity && args_info->l_orbital_qn_given))
            {
              fprintf (stderr, "%s: `--l-orbital-qn' (`-l') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->l_orbital_qn_given && ! override)
            continue;
          local_args_info.l_orbital_qn_given = 1;
          args_info->l_orbital_qn_given = 1;
          args_info->l_orbital_qn_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->l_orbital_qn_orig)
            free (args_info->l_orbital_qn_orig); /* free previous string */
          args_info->l_orbital_qn_orig = gengetopt_strdup (optarg);
          break;

        case 'j':	/* Total angular momentum quantum number, e.g. for H 1s electon orbit (l = 0, s = 1/2) it would be 0+0.5 = 0.5, etc.  */
          if (local_args_info.j_total_qn_given || (check_ambiguity && args_info->j_total_qn_given))
            {
              fprintf (stderr, "%s: `--j-total-qn' (`-j') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->j_total_qn_given && ! override)
            continue;
          local_args_info.j_total_qn_given = 1;
          args_info->j_total_qn_given = 1;
          args_info->j_total_qn_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->j_total_qn_orig)
            free (args_info->j_total_qn_orig); /* free previous string */
          args_info->j_total_qn_orig = gengetopt_strdup (optarg);
          break;

        case 'Z':	/* Charge of nucleus, e.g. 2 for alpha, etc..  */
          if (local_args_info.Z_nucl_charge_given || (check_ambiguity && args_info->Z_nucl_charge_given))
            {
              fprintf (stderr, "%s: `--Z-nucl-charge' (`-Z') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->Z_nucl_charge_given && ! override)
            continue;
          local_args_info.Z_nucl_charge_given = 1;
          args_info->Z_nucl_charge_given = 1;
          args_info->Z_nucl_charge_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->Z_nucl_charge_orig)
            free (args_info->Z_nucl_charge_orig); /* free previous string */
          args_info->Z_nucl_charge_orig = gengetopt_strdup (optarg);
          break;


        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
